Adapt Omarchy 4.0.2 RC for generic AArch64 virtual machines

diff --git a/bin/omarchy-refresh-pacman b/bin/omarchy-refresh-pacman
--- a/bin/omarchy-refresh-pacman
+++ b/bin/omarchy-refresh-pacman
@@ -6,18 +6,25 @@
 sudo cp -f /etc/pacman.conf /etc/pacman.conf.bak
 sudo cp -f /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.bak
 
-channel="${1:-stable}"
+if [[ -f /etc/omarchy-aarch64/profile ]]; then
+  echo "Refreshing the Arch Linux ARM repositories"
+  echo
+  sudo cp -f "$OMARCHY_PATH/default/pacman/pacman-aarch64.conf" /etc/pacman.conf
+  sudo cp -f "$OMARCHY_PATH/default/pacman/mirrorlist-aarch64" /etc/pacman.d/mirrorlist
+else
+  channel="${1:-stable}"
 
-if [[ $channel != "stable" && $channel != "rc" && $channel != "edge" ]]; then
-  echo "Error: Invalid channel '$channel'. Must be one of: stable, rc, edge"
-  exit 1
+  if [[ $channel != "stable" && $channel != "rc" && $channel != "edge" ]]; then
+    echo "Error: Invalid channel '$channel'. Must be one of: stable, rc, edge"
+    exit 1
+  fi
+
+  echo "Setting channel to $channel"
+  echo
+
+  sudo cp -f "$OMARCHY_PATH/default/pacman/pacman-$channel.conf" /etc/pacman.conf
+  sudo cp -f "$OMARCHY_PATH/default/pacman/mirrorlist-$channel" /etc/pacman.d/mirrorlist
 fi
-
-echo "Setting channel to $channel"
-echo
-
-sudo cp -f "$OMARCHY_PATH/default/pacman/pacman-$channel.conf" /etc/pacman.conf
-sudo cp -f "$OMARCHY_PATH/default/pacman/mirrorlist-$channel" /etc/pacman.d/mirrorlist
 
 # Allow user customization of /etc/pacman.conf before the upgrade runs
 omarchy-hook pre-refresh-pacman
